name: fireproof_riverpod
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fireproof:
    git:
      url: https://github.com/Nolence/fireproof.git
      path: ./packages/fireproof

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  cloud_firestore: ^2.3.0
  flutter_riverpod: ^0.14.0+3
  kt_dart: ^0.9.1

dependency_overrides:
  fireproof:
    path: ../fireproof

flutter:
