name: fireproof
description: To be used as a common interface to deal with riverpod \
  and firestore using abstractions such as document and a handler to deal \
  with pagination etc.
version: 0.0.3
homepage: https://pub.dev/packages/fireproof

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  cloud_firestore: ^2.3.0
  state_notifier: ^0.7.0
  rxdart: ^0.27.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  freezed:
  build_runner: