name: hooks_fireproof_storage
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.4
  firebase_storage: ^10.0.1
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: null
